export const greetings: Record<string, string> = {
  Afrikaans: "Hallo",
  Albanian: "P\u00ebrsh\u00ebndetje",
  Amharic: "Iwi selami newi",
  Arabic: "Marhaba",
  Armenian: "Barev",
  Aymara: "Kamisaki",
  Azerbaijani: "Salam",
  Basque: "Kaixo",
  Belarusian: "Vitaju",
  Bengali: "Hy\u0101l\u014d",
  Bosnian: "Zdravo",
  Bulgarian: "Zdravei\u0306te",
  Burmese: "Haallo",
  Cantonese: "N\u01d0 h\u01ceo",
  Catalan: "Hola",
  Cebuano: "Kamusta",
  Chichewa: "Moni",
  Corsican: "Bonghjornu",
  Croatian: "Zdravo",
  Czech: "Ahoj",
  Danish: "Hej",
  Dutch: "Hallo",
  English: "Hello",
  Estonian: "Tere",
  Ewe: "Hello",
  Farsi: "Sal\u0101m",
  Fijian: "Bula",
  Filipino: "Kumusta",
  Finnish: "Hei",
  French: "Bonjour",
  Gaelic: "Dia dhuit",
  Galician: "Ola",
  Georgian: "Gamarjoba",
  German: "Guten tag",
  Greek: "Geia",
  Guarani: "Mba'\u00e9ichapa",
  "Haitian Creole": "Bonjou",
  Hawaiian: "Aloha",
  Hebrew: "Shalom",
  Hindi: "Namaste",
  Hmong: "Nyob zoo",
  Hungarian: "Szia",
  Icelandic: "Hall\u00f3",
  Igbo: "Ndewo",
  Ilocano: "Hello",
  Indonesian: "Halo",
  Italian: "Ciao",
  Japanese: "Konichiwa",
  Kazakh: "S\u00e4lemetsiz be",
  Khmer: "Suostei",
  Kinyarwanda: "Mwaramutse",
  Korean: "Anyeong haseyo",
  Kurdish: "Slav",
  Lao: "Sabaidi",
  Latin: "Salve",
  Latvian: "Sveika",
  Lithuanian: "Sveiki",
  Luxembourgish: "Moien",
  Malagasy: "Salama",
  Malay: "Selamat pagi",
  Maltese: "Bongu",
  Mandarin: "N\u01d0 h\u01ceo",
  Maori: "Kia ora",
  Marathi: "Namask\u0101ra",
  Mongolian: "Sain uu",
  Nahuatl: "Niltze Tialli Pialli",
  Navajo: "Ya\u2019at\u2019eeh",
  Nepali: "Namask\u0101ra",
  Norwegian: "Hei",
  Pashto: "Salam",
  Polish: "Cze\u015b\u0107",
  Portuguese: "Ol\u00e1",
  Punjabi: "Sata sr\u012b ak\u0101la",
  Oromo: "Akkam",
  Quechua: "Allianchu",
  Romanian: "Bun\u00e2",
  Russian: "Privet",
  Samoan: "Talofa",
  Sepedi: "Thobela",
  Serbian: "Zdravo",
  Sesotho: "Dumela",
  Slovak: "Ahoj",
  Slovenian: "Zdravo",
  Somali: "Hello",
  Spanish: "Hola",
  Swahili: "Jambo",
  Swedish: "Hall\u00e5",
  Tagalog: "Kamusta",
  Tahitian: "Ia Orana",
  Taiwanese: "Li-h\u00f3",
  Tamil: "Vanakkam",
  Thai: "S\u0304w\u1ea1s\u0304d\u012b",
  Tibetan: "Tashi delek",
  Tongan: "M\u0101l\u014d e lelei",
  Tsonga: "Avuxeni",
  Turkish: "Merhaba",
  Ukrainian: "Privit",
  Urdu: "Assal\u0101mu Alaykum",
  Uzbek: "Salom",
  Vietnamese: "Xin ch\u00e0o",
  Welsh: "Helo",
  Xhosa: "Molo",
} as const

export function getRandomGreeting(): [string, string] {
  const keys = Object.keys(greetings)
  const randomKey = keys[Math.floor(Math.random() * keys.length)]
  return [randomKey, greetings[randomKey]]
}
