package model

import (
	"database/sql"
	"gorm.io/gorm"
	"time"
)

// User represents a user which can log in (obviously)
type User struct {
	// ID is generated by firebase (in the best case)
	ID string `gorm:"primaryKey" json:"id,omitempty"`
	// Name is the username which is displayed in the frontend
	Name string `json:"name,omitempty"`
	// CreatedAt is the time when the entry was first created
	CreatedAt time.Time `json:"createdAt"`
	// UpdatedAt is the time when the entry was modified
	UpdatedAt time.Time `json:"updatedAt"`
	// DeletedAt is the time when the entry was (soft-) removed
	DeletedAt gorm.DeletedAt `gorm:"index" json:"deletedAt"`
	// OwnerProjects contains a list of all projects the user is owner of
	OwnerProjects []Project `gorm:"foreignKey:OwnerID" json:"ownerProjects,omitempty"`
	// UserProjects contains a list of all projects the user has access to
	UserProjects []Project `gorm:"many2many:user_projects;" json:"userProjects,omitempty"`
}

// Comment represents a comment in a topic
type Comment struct {
	gorm.Model
	// AuthorID is the id of the author of the comment
	AuthorID string `json:"authorID,omitempty"`
	// Author is the author of the comment
	Author User `json:"author"`
	// Content is the comment content as markdown
	Content string `json:"content,omitempty"`
	// TopicID is the ID of the topic the comment belongs to
	TopicID uint `json:"topicID,omitempty"`
}

// Topic represents a ToDo-Point for the meeting
type Topic struct {
	gorm.Model
	// Title of the topic
	Title string `json:"title,omitempty"`
	// Description of the topic
	Description string `json:"description,omitempty"`
	// ID of the creator of the topic
	CreatorID string `json:"creatorID,omitempty"`
	// Creator of the topic
	Creator User `json:"creator"`
	// Comments in the topic
	Comments []Comment `json:"comments,omitempty"`
	// SolutionID is the ID of the comment which represents the solution of this topic
	SolutionID uint `json:"solutionID,omitempty"`
	// Solution is the comment which represents the solution of this topic
	Solution Comment `json:"solution"`
	// ClosedAt represents the time when the topic was resolved (if valid)
	ClosedAt sql.NullTime `json:"closedAt"`
	// ForceSolution requires a solution to be able to close topic if true
	ForceSolution bool `json:"forceSolution,omitempty"`
	// MeetingID is the ID of the meeting the topic belongs to
	MeetingID uint `json:"meetingID,omitempty"`
}

// Meeting represents a meeting (who would've guessed)
type Meeting struct {
	gorm.Model
	// Name if the meeting
	Name string `json:"name,omitempty"`
	// StartDate of the meeting
	StartDate time.Time `json:"startDate"`
	// Topics of the meeting
	Topics []Topic `json:"topics,omitempty"`
	// ProjectID is the project the meeting belongs to
	ProjectID uint `json:"projectID,omitempty"`
}

// Project is a custom "realm" where meetings are saved
type Project struct {
	gorm.Model
	// Name is the name of the project and displayed in the frontend
	Name string `json:"name,omitempty"`
	// Description of the project
	Description string `json:"description,omitempty"`
	// PreviewURL is the display image
	PreviewURL string `json:"previewURL,omitempty"`
	// OwnerID is the id of the creator of the project
	OwnerID string `json:"ownerID,omitempty"`
	// Owner is the creator of the project
	Owner User `json:"owner"`
	// Users contains all users which have access to the project
	Users []User `gorm:"many2many:user_projects;" json:"users,omitempty"`
	// Meetings contains all meetings in the project
	Meetings []Meeting `json:"meetings,omitempty"`
}
